name: CI Simple If

on:
  push:
    branches: [main]

jobs:
  hello:
    name: Hello World
    runs-on: ubuntu-latest
    if: true
    steps:
      - run: echo "Hello from CI"

  skip-me:
    name: Skip Me
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo "This should be skipped"
