name: CI HashFiles If

on:
  push:
    branches: [main]

jobs:
  hello:
    name: Has pyproject
    runs-on: ubuntu-latest
    if: ${{ hashFiles('pyproject.toml') != '' }}
    steps:
      - run: echo "pyproject.toml found"

  skip-no-lockfile:
    name: No lockfile
    runs-on: ubuntu-latest
    if: ${{ hashFiles('package-lock.json') != '' }}
    steps:
      - run: echo "This should skip"
